### ISSUE TITLE
 Error when starting components

### ISSUE THREAD

**Issue by leoratto** [mitmedialab/medrec#14]
I followed the steps in item 1 - For production and the moment I started the components of medrec it is as follows (attachment)

can you help me?

![medrec](https://user-images.githubusercontent.com/60516922/73565255-ee4eee00-443f-11ea-9cde-0caccc314c44.jpg)

**Comment by agnescameron** [comment]
Hi leoratto -- without more information as to what you've tried it's hard to debug your problem. From the screen on the right, it looks like your ganache server is not running. 

Can you try following the Development rather than Production instructions? You will get more detailed error messages that way.

**Comment by Firescar96** [comment]
This project is somewhat old now (ancient in computer years) and the software packages we used for the UserClient have undergone many breaking changes. I'm not sure what broke with the UserClient and none of the original architects are still working on this project. If you are able to figure it out please submit a pull request.
